### ISSUE TITLE
ScreenTask v1.2 doesn't work on Windows 10 Enterprise LTSC 21H2

### ISSUE THREAD

**Issue by skylandersNFC** [EslaMx7/ScreenTask#67]
Hi there,

**Issue Summary**

I encountered an unusual issue with the "ScreenTask v1.2" app.
It was running flawlessly on my Windows 10 Enterprise LTSC 21H2 system.
I even set it up to autostart on this server without any problems.
Everything was working perfectly until, unexpectedly, it stopped functioning.

**Problem Description**

The .exe launches and creates an icon in the system tray, but no active URL is generated, and there's no way to interact with it.
When I try to open the icon from the system tray, it disappears immediately.

**Troubleshooting Steps**

 I have .NET Framework 4.5 installed, and the app was previously working without any issues.
 I have a second server where the app still works, so I copied the "**appsettings.xml**" configuration file from there for testing purposes.

**Configuration File**

`<?xml version="1.0"?>
<AppSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <IP>192.168.1.100</IP>
  <Port>7092</Port>
  <ScreenshotsSpeed>500</ScreenshotsSpeed>
  <IsPrivateSession>false</IsPrivateSession>
  <Username>screen</Username>
  <Password>task</Password>
  <SelectedScreenIndex>0</SelectedScreenIndex>
  <IsShowMouseEnabled>true</IsShowMouseEnabled>
  <IsAutoStartServerEnabled>true</IsAutoStartServerEnabled>
  <IsStartMinimizedEnabled>true</IsStartMinimizedEnabled>
  <ImageQuality>100</ImageQuality>
</AppSettings>`

Based on this configuration, the ScreenTask should be accessible at: `http://192.168.1.100:7092/`.
The IP address is correct for this machine and the port is unused.

Despite this, I'm unable to reach the endpoint; it seems the server isn't responding.
It's also not a firewall issue, as I'm not even able to reach it locally (from the same machine).

**Question**

Are there any hidden debug options or ways to enable a debug mode?
I'd like to start the application with console logs or some debug output so I can trace what might be going wrong.

Any insights or suggestions would be appreciated!

**Comment by skylandersNFC** [comment]
P.S. I suspect that the app is crashing on launch, as it doesn't appear in any of my active application lists.
This would also explain why the icon disappears from the system tray when I hover over it.
It seems that the system tray refreshes once it detects that the icon is pointing to a non-existent object, indicating the app might not be running at all.

**Comment by skylandersNFC** [comment]
My Application Logs are giving me this :

**.NET Runtime**

Application: ScreenTask.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.PlatformNotSupportedException
   at System.Net.HttpListener..ctor()
   at ScreenTask.frmMain..ctor()
   at ScreenTask.Program.Main()

**Application Error**

Faulting application name: ScreenTask.exe, version: 1.2.0.0, time stamp: 0x6214b58d
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3031, time stamp: 0x7431a292
Exception code: 0xe0434352
Fault offset: 0x0013d8a2
Faulting process id: 0xe9c
Faulting application start time: 0x01db245a10a49b31
Faulting application path: C:\Program Files (x86)\ScreenTask\ScreenTask.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: a6a4bc34-cbed-4e87-bc14-d29a4156cc9c
Faulting package full name: 
Faulting package-relative application ID:
